// Standard API error codes returned by the OpenWA API.
// Format: SCREAMING_SNAKE_CASE, grouped by domain.

export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  EXPIRED_API_KEY: 'EXPIRED_API_KEY',
  REVOKED_API_KEY: 'REVOKED_API_KEY',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  TENANT_INACTIVE: 'TENANT_INACTIVE',

  // Rate limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

  // Sessions
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NAME_TAKEN: 'SESSION_NAME_TAKEN',
  SESSION_NOT_CONNECTED: 'SESSION_NOT_CONNECTED',
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  SESSION_BAD_STATE: 'SESSION_BAD_STATE',

  // Messages
  RECIPIENT_NOT_ON_WHATSAPP: 'RECIPIENT_NOT_ON_WHATSAPP',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',

  // Webhooks
  WEBHOOK_URL_INVALID: 'WEBHOOK_URL_INVALID',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  requestId?: string;
}

export interface ApiErrorResponse {
  error: ApiError;
}
